#!/usr/bin/env ruby

require 'sample'

current = Asbo::Sample.new
tests_passed = Asbo::Sample.load('tests_passed.sample')
diff = tests_passed.diff(current)

if diff[:svn_diff_md5]
  puts %q{
                      8888888b.  888     888 888b    888 
                      888   Y88b 888     888 8888b   888 
                      888    888 888     888 88888b  888 
                      888   d88P 888     888 888Y88b 888 
                      8888888P"  888     888 888 Y88b888 
                      888 T88b   888     888 888  Y88888 
                      888  T88b  Y88b. .d88P 888   Y8888 
                      888   T88b  "Y88888P"  888    Y888 
                                                         
                                                         
                                                         
             88888888888 8888888888 .d8888b. 88888888888 .d8888b.  
                 888     888       d88P  Y88b    888    d88P  Y88b 
                 888     888       Y88b.         888    Y88b.      
                 888     8888888    "Y888b.      888     "Y888b.   
                 888     888           "Y88b.    888        "Y88b. 
                 888     888             "888    888          "888 
                 888     888       Y88b  d88P    888    Y88b  d88P 
                 888     8888888888 "Y8888P"     888     "Y8888P"  
  }
  puts "Tests have not been run with current set of changes."
  exit(1)
end

if diff[:svn_base_revision]
  puts %q{
                       .d8888b.  888     888 888b    888 
                      d88P  Y88b 888     888 8888b   888 
                      Y88b.      888     888 88888b  888 
                       "Y888b.   Y88b   d88P 888Y88b 888 
                          "Y88b.  Y88b d88P  888 Y88b888 
                            "888   Y88o88P   888  Y88888 
                      Y88b  d88P    Y888P    888   Y8888 
                       "Y8888P"      Y8P     888    Y888 
                                                         
                                                         
                                                         
     888     888 8888888b.  8888888b.        d8888 88888888888 8888888888 
     888     888 888   Y88b 888  "Y88b      d88888     888     888        
     888     888 888    888 888    888     d88P888     888     888        
     888     888 888   d88P 888    888    d88P 888     888     8888888    
     888     888 8888888P"  888    888   d88P  888     888     888        
     888     888 888        888    888  d88P   888     888     888        
     Y88b. .d88P 888        888  .d88P d8888888888     888     888        
      "Y88888P"  888        8888888P" d88P     888     888     8888888888 
  }
  puts "Tests have not been run with latest repository revision."
  exit(1)
end

